# Generated by Django 5.1.5 on 2025-05-23 18:11

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='banners/%Y/%m/%d')),
                ('is_publish', models.BooleanField(default=True)),
                ('banner_type', models.CharField(blank=True, choices=[('coach', 'coach'), ('student', 'student'), ('public', 'public')], help_text='Banner type', max_length=7)),
            ],
            options={
                'db_table': 'banner',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HeaderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('header_title', models.CharField(blank=True, help_text='عنوان هدر', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_title/%Y/%m/%d', validators=[utils.validators.file_upload_validator])),
                ('is_publish', models.BooleanField(default=True)),
                ('text_color', models.CharField(blank=True, max_length=15)),
                ('background_color', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'header_site',
            },
        ),
    ]
