# Generated by Django 5.1.5 on 2025-04-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-created_at',)},
        ),
    ]
