# Generated by Django 5.1.5 on 2025-04-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0002_alter_banner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(blank=True, choices=[('coach', 'coach'), ('student', 'student')], help_text='Banner type', max_length=7),
        ),
    ]
