# Generated by Django 5.1.5 on 2025-04-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0003_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(blank=True, choices=[('coach', 'coach'), ('student', 'student'), ('public', 'public')], help_text='Banner type', max_length=7),
        ),
    ]
