# Generated by Django 5.1.5 on 2025-04-20 14:51

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0004_alter_banner_banner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('header_title', models.CharField(blank=True, help_text='عنوان هدر', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_title/%Y/%m/%d', validators=[utils.validators.file_upload_validator])),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'header_site',
            },
        ),
    ]
