# Generated by Django 5.1.5 on 2025-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0005_headersite'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersite',
            name='background_color',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='headersite',
            name='text_color',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
