# Generated by Django 5.1.5 on 2025-07-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_usercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='for_first',
        ),
    ]
