# Generated by Django 5.1.5 on 2025-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_usage',
            field=models.PositiveIntegerField(blank=True, help_text='توسط کاربر چند بار استفاده شود', null=True, verbose_name='حداکثر استفاده'),
        ),
    ]
