# Generated by Django 5.1.5 on 2025-05-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='for_first',
            field=models.BooleanField(default=False),
        ),
    ]
