# Generated by Django 5.1.5 on 2025-04-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-created_at',)},
        ),
    ]
