# Generated by Django 5.1.5 on 2025-05-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('discount_app', '0002_alter_coupon_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='course',
        ),
        migrations.AddField(
            model_name='discount',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='discount',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['content_type', 'object_id'], name='discount_ap_content_763648_idx'),
        ),
    ]
