# Generated by Django 5.1.5 on 2025-05-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_remove_discount_course_discount_content_type_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='discount',
            new_name='discount_ap_content_a62fa8_idx',
            old_name='discount_ap_content_763648_idx',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='discount_app',
        ),
    ]
