# Generated by Django 5.1.5 on 2025-05-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_alter_coupon_valid_from_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together=set(),
        ),
    ]
