# Generated by Django 5.1.5 on 2025-05-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('discount_app', '0004_rename_discount_ap_content_763648_idx_discount_ap_content_a62fa8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discount',
            name='discount_ap_content_a62fa8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together={('content_type', 'object_id')},
        ),
    ]
