# Generated by Django 5.1.5 on 2025-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapentry',
            name='last_modified',
            field=models.CharField(blank=True),
        ),
    ]
