# Generated by Django 5.1.2 on 2024-11-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("comment_body", models.TextField(verbose_name="تن کامنت")),
                (
                    "is_publish",
                    models.BooleanField(default=True, verbose_name="انشتار"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={"is_publish": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_comment",
                        to="course.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={
                            "is_active": True,
                            "is_deleted": False,
                            "is_student": True,
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "db_table": "course_comment",
            },
        ),
    ]
