# Generated by Django 5.1.5 on 2025-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionvideo",
            name="title",
            field=models.CharField(help_text="عنوان", max_length=50, null=True),
        ),
    ]
