# Generated by Django 5.1.5 on 2025-02-11 20:58

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                upload_to="course_image/%Y/%m/%d",
                validators=[course.validators.max_upload_image_validator],
            ),
        ),
    ]
