# Generated by Django 5.1.5 on 2025-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
