# Generated by Django 5.1.5 on 2025-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollment",
            name="status",
            field=models.CharField(
                choices=[("active", "فعال"), ("dropped", "ترک شده")],
                default="active",
                max_length=7,
            ),
        ),
    ]
