# Generated by Django 5.1.5 on 2025-03-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("-created_at",),
                "permissions": [("can_view_course", "Can View Course")],
                "verbose_name": "درس",
                "verbose_name_plural": "درس ها",
            },
        ),
    ]
