# Generated by Django 5.1.5 on 2025-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="practice",
        ),
        migrations.AddField(
            model_name="practice",
            name="is_close",
            field=models.BooleanField(
                default=False, help_text="تمرین بسته شده هست یا خیر"
            ),
        ),
    ]
