# Generated by Django 5.1.5 on 2025-05-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_pined',
            field=models.BooleanField(default=False),
        ),
    ]
