# Generated by Django 5.1.5 on 2025-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_comment_options_category_description_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
