# Generated by Django 5.1.5 on 2025-03-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessCourse",
        ),
    ]
