# Generated by Django 5.1.5 on 2025-03-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_practice_practice_practice_is_close"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsectionscore",
            name="student",
        ),
    ]
