# Generated by Django 5.1.5 on 2025-02-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_studentenrollment_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together=set(),
        ),
    ]
