# Generated by Django 5.1.5 on 2025-02-11 23:37

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                help_text="حداکثر اندازه عکس 1 مگابایت هست",
                upload_to="course_image/%Y/%m/%d",
                validators=[course.validators.max_upload_image_validator],
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_image",
            field=models.ImageField(
                help_text="حداکثر اندازه سایز عکس برابر است با 1 مگابایت هست",
                upload_to="course_section/%Y/%m/%d",
                validators=[course.validators.max_upload_image_validator],
            ),
        ),
    ]
