# Generated by Django 5.1.5 on 2025-02-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_course_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="student",
        ),
        migrations.RemoveField(
            model_name="course",
            name="teacher",
        ),
    ]
