# Generated by Django 5.1.5 on 2025-02-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_coachenrollment_is_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachenrollment",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
    ]
