# Generated by Django 5.1.5 on 2025-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_referral_code_invitation'),
        ('course', '0002_comment_is_pined'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('section', 'student')},
        ),
    ]
