# Generated by Django 5.1.2 on 2024-12-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0002_alter_course_options_alter_term_options_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practice",
            options={"verbose_name": "تمرین", "verbose_name_plural": "تمرین ها"},
        ),
        migrations.AddField(
            model_name="practice",
            name="coach",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="practice",
                to="accounts.coach",
            ),
            preserve_default=False,
        ),
    ]
