# Generated by Django 5.1.5 on 2025-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_rename_term_name_category_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="term",
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ManyToManyField(
                related_name="course_category", to="course.category"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_duration",
            field=models.CharField(help_text="مدت زمان دوره", max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_price",
            field=models.FloatField(help_text="قیمت دوره"),
        ),
    ]
