# Generated by Django 5.1.2 on 2024-11-08 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={"is_publish": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_courses",
                        to="course.course",
                        verbose_name="درس",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={
                            "is_active": True,
                            "is_coach": True,
                            "is_deleted": False,
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_professor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="استاد",
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        limit_choices_to={
                            "is_active": True,
                            "is_deleted": False,
                            "is_student": True,
                        },
                        related_name="student_quiz",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دانشجویان",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quzi_term",
                        to="course.term",
                        verbose_name="ترم",
                    ),
                ),
            ],
            options={
                "verbose_name": "کویز",
                "verbose_name_plural": "کویزها",
                "db_table": "quiz",
            },
        ),
    ]
