# Generated by Django 5.1.5 on 2025-03-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0002_studentenrollment_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentenrollment",
            name="coach",
        ),
        migrations.RemoveField(
            model_name="coachenrollment",
            name="coach",
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="student",
        ),
        migrations.CreateModel(
            name="StudentByCoach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="students_by_coach",
                        to="accounts.coach",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_choice",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_by_coach",
            },
        ),
        migrations.AddField(
            model_name="coachenrollment",
            name="coach",
            field=models.ManyToManyField(
                related_name="coach_enrollment", to="accounts.coach"
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="student",
            field=models.ManyToManyField(
                related_name="students", to="accounts.student"
            ),
        ),
    ]
