# Generated by Django 5.1.5 on 2025-02-08 13:39

import django.core.validators
import utils.file_name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_sectionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                upload_to=utils.file_name.section_filename,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="video",
            field=models.FileField(
                blank=True,
                upload_to=utils.file_name.section_name,
                validators=[django.core.validators.FileExtensionValidator(["mp4"])],
            ),
        ),
    ]
