# Generated by Django 5.1.5 on 2025-03-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_sectionvideo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionfile",
            name="expired_data",
            field=models.DateTimeField(help_text="زمان انتقضای تمرین"),
        ),
    ]
