# Generated by Django 5.1.2 on 2024-11-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_course_course_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="depth",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="path",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
