# Generated by Django 5.1.5 on 2025-03-17 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0003_alter_sectionfile_expired_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentAbsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "lesson_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lesson_present_absent",
                        to="course.lessoncourse",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_present_absent",
                        to="course.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_present_absent",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "db_table": "course_section_present_absent",
                "ordering": ("-created_at",),
            },
        ),
    ]
