# Generated by Django 5.1.2 on 2024-12-13 08:18

import django.utils.timezone
import utils.file_name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_practice_options_practice_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="practice",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="practice",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="practice",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="practice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="practice",
            name="practice_file",
            field=models.FileField(upload_to=utils.file_name.practice_name),
        ),
    ]
