# Generated by Django 5.1.5 on 2025-03-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_remove_studentenrollment_coach_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachenrollment",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="is_active",
        ),
    ]
