# Generated by Django 5.1.5 on 2025-02-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_course_course_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
    ]
