# Generated by Django 5.1.5 on 2025-02-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_studentenrollment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teacherenrollment",
            unique_together=set(),
        ),
    ]
