# Generated by Django 5.1.5 on 2025-02-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_coachenrollment_is_publish"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coachenrollment",
            old_name="is_publish",
            new_name="is_active",
        ),
    ]
