# Generated by Django 5.1.2 on 2024-11-04 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_depth_course_numchild_course_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={"is_publosh": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_selection_courses",
                        to="course.course",
                        verbose_name="درس",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_coach": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_selection_professor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="استاد",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_selection_term",
                        to="course.term",
                        verbose_name="ترم",
                    ),
                ),
            ],
            options={
                "verbose_name": "انتخاب درس",
                "verbose_name_plural": "انتخاب درس ها",
                "db_table": "unit_selection",
                "ordering": ("-created_at",),
            },
        ),
    ]
