# Generated by Django 5.1.5 on 2025-03-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0003_remove_studentsectionscore_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsectionscore",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_section_score",
                to="accounts.student",
            ),
        ),
    ]
