# Generated by Django 5.1.5 on 2025-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_remove_course_student_remove_course_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="sectionimage",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="teacherenrollment",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
