# Generated by Django 5.1.2 on 2024-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="term",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="unitselection",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
