# Generated by Django 5.1.5 on 2025-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_description_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupcourse',
            name='referral_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
