# Generated by Django 5.1.5 on 2025-07-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otp_options_alter_user_nation_code'),
        ('course', '0004_signupcourse_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/pdf/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='certificates/qr_codes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='unique_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_certificates', to='course.section'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_certificates', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_last_section',
            field=models.BooleanField(default=False, help_text='اگر تیک این مورد خورده باشد یعنی اخرین سکشن برای درس خواهد بود'),
        ),
        migrations.AlterModelTable(
            name='certificate',
            table=None,
        ),
    ]
