# Generated by Django 5.1.5 on 2025-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_category_is_deleted_alter_comment_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="sectionimage",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="sectionimage",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="teacherenrollment",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="teacherenrollment",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
