# Generated by Django 5.1.2 on 2024-12-13 09:12

import django.core.validators
import utils.file_name
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_practice_created_at_practice_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="section",
            name="video",
            field=models.FileField(
                upload_to=utils.file_name.course_name,
                validators=[
                    django.core.validators.FileExtensionValidator("mp4"),
                    utils.validators.file_upload_validator,
                ],
            ),
        ),
    ]
