# Generated by Django 5.1.5 on 2025-02-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_remove_course_category_course_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_category",
                to="course.category",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
    ]
