# Generated by Django 5.1.5 on 2025-05-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
