# Generated by Django 5.1.5 on 2025-03-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_options_coachaccesscourse_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coachaccesscourse",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="sendsectionfile",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="studentaccesscourse",
            options={"ordering": ("-created_at",)},
        ),
    ]
