# Generated by Django 5.1.5 on 2025-02-15 21:26

import course.validators
import django.core.validators
import django.db.models.deletion
import utils.file_name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_course_is_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="section",
            name="section_image",
        ),
        migrations.RemoveField(
            model_name="section",
            name="video",
        ),
        migrations.CreateModel(
            name="SectionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to=utils.file_name.section_filename,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_files",
                        to="course.section",
                    ),
                ),
            ],
            options={
                "db_table": "course_section_file",
            },
        ),
        migrations.CreateModel(
            name="SectionImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                (
                    "section_image",
                    models.ImageField(
                        help_text="حداکثر اندازه سایز عکس برابر است با 1 مگابایت هست",
                        upload_to="course_section/%Y/%m/%d",
                        validators=[course.validators.max_upload_image_validator],
                    ),
                ),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_images",
                        to="course.section",
                    ),
                ),
            ],
            options={
                "db_table": "course_section_images",
            },
        ),
        migrations.CreateModel(
            name="SectionVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                (
                    "video",
                    models.FileField(
                        upload_to="section_video/%Y/%m/%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(["mp4"])
                        ],
                    ),
                ),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_videos",
                        to="course.section",
                    ),
                ),
            ],
            options={
                "db_table": "course_section_video",
            },
        ),
    ]
