# Generated by Django 5.1.5 on 2025-02-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0004_rename_is_publish_coachenrollment_is_active"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Enrollment",
            new_name="StudentEnrollment",
        ),
    ]
