# Generated by Django 5.1.2 on 2024-11-17 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_comment_is_deleted_alter_course_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "is_deleted": False},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="student",
            field=models.ManyToManyField(
                limit_choices_to={"is_active": True, "is_deleted": False},
                related_name="student_quiz",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دانشجویان",
            ),
        ),
        migrations.AlterField(
            model_name="unitselection",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
