# Generated by Django 5.1.5 on 2025-02-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_teacherenrollment_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherenrollment",
            options={"ordering": ["-created_at"]},
        ),
    ]
