# Generated by Django 5.1.5 on 2025-03-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_remove_coachenrollment_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentbycoach",
            name="is_active",
        ),
        migrations.AddField(
            model_name="studentbycoach",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_coach_students",
                to="course.course",
            ),
            preserve_default=False,
        ),
    ]
