# Generated by Django 5.1.5 on 2025-02-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_rename_enrollment_studentenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionfile",
            name="title",
            field=models.CharField(help_text="عنوان", max_length=100, null=True),
        ),
    ]
