# Generated by Django 5.1.5 on 2025-03-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_coachaccesscourse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessoncourse",
            name="progress",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("Started", "Started"),
                    ("Finished", "Finished"),
                    ("In Progress", "In Progress"),
                ],
                default="Not Started",
                help_text="وضعیت پیشرفت دوره",
                max_length=11,
            ),
        ),
    ]
