# Generated by Django 5.1.5 on 2025-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0005_remove_studentbycoach_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentbycoach",
            name="student",
        ),
        migrations.AddField(
            model_name="studentbycoach",
            name="student",
            field=models.ManyToManyField(
                related_name="student_choice", to="accounts.student"
            ),
        ),
    ]
