# Generated by Django 5.1.5 on 2025-05-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_section_title'),
        ('images', '0002_alter_image_options_remove_image_focal_point_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_certificate', to='images.image'),
        ),
    ]
