# Generated by Django 5.1.5 on 2025-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_certificate_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='unique_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
