# Generated by Django 5.1.5 on 2025-03-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_presentabsent_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentabsent",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="section_present_absent",
                to="course.studentaccesssection",
            ),
        ),
    ]
