# Generated by Django 5.1.5 on 2025-02-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_course_category_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "درس",
                "verbose_name_plural": "درس ها",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_category",
                to="course.category",
            ),
        ),
    ]
