# Generated by Django 5.1.5 on 2025-02-16 20:37

import course.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course",
            "0005_remove_section_pdf_file_remove_section_section_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionfile",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                upload_to="section_file/%Y/%m/%d",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="sectionimages",
            name="section_image",
            field=models.ImageField(
                help_text="حداکثر اندازه سایز عکس برابر است با 1 مگابایت هست",
                upload_to="course_section_images/%Y/%m/%d",
                validators=[course.validators.max_upload_image_validator],
            ),
        ),
    ]
