# Generated by Django 5.1.5 on 2025-03-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_remove_studentbycoach_student_studentbycoach_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentbycoach",
            options={"ordering": ["created_at"]},
        ),
    ]
