# Generated by Django 5.1.5 on 2025-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_sectionfile_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionfile",
            name="expired_data",
            field=models.DateTimeField(help_text="زمان انتقضای تمرین", null=True),
        ),
    ]
