# Generated by Django 5.1.5 on 2025-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_category_is_deleted_alter_comment_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_price",
            field=models.FloatField(help_text="قیمت دوره که بر اساس تومان میباشد"),
        ),
        migrations.AlterField(
            model_name="section",
            name="is_available",
            field=models.BooleanField(default=True, help_text="در دسترس بودن"),
        ),
    ]
