# Generated by Django 5.1.5 on 2025-02-17 14:46

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_sectionfile_pdf_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="cover_image",
            field=models.ImageField(
                null=True,
                upload_to="section_cover_image/%Y/%m/%d",
                validators=[course.validators.max_upload_image_validator],
            ),
        ),
        migrations.DeleteModel(
            name="SectionImages",
        ),
    ]
