# Generated by Django 5.1.5 on 2025-03-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_presentabsent_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendpractice",
            name="practice",
        ),
        migrations.RemoveField(
            model_name="sendpractice",
            name="student",
        ),
        migrations.RemoveField(
            model_name="sectionfile",
            name="expired_data",
        ),
        migrations.RemoveField(
            model_name="sectionfile",
            name="is_close",
        ),
        migrations.DeleteModel(
            name="Practice",
        ),
        migrations.DeleteModel(
            name="SendPractice",
        ),
    ]
