# Generated by Django 5.1.5 on 2025-07-04 21:17

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_certificate_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('template_image', models.ImageField(help_text='حداکثر اندازه سایز تمپلیت ۲ مگابایت باشد', upload_to='certificate_template/%Y/%m/%d', validators=[course.validators.max_upload_image_validator])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'certificate_template',
            },
        ),
    ]
