# Generated by Django 5.1.2 on 2024-12-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_ticket_admin_ticket_user"),
        ("course", "0006_practice_expired_practice_practice_practice_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "coach",
                    models.ManyToManyField(
                        related_name="class_room_coach", to="accounts.coach"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="course_classroom",
                        to="course.course",
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="class_room_user", to="accounts.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "کلاس درسی",
                "verbose_name_plural": "کلاس های درسی",
                "db_table": "class_room",
            },
        ),
    ]
