# Generated by Django 5.1.5 on 2025-05-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_last_section',
            field=models.BooleanField(default=False, help_text='اگر این مقدار برابر با ترو باشد یعنی اخرین سکشن برای درس خواهد بود'),
        ),
    ]
