# Generated by Django 5.1.5 on 2025-02-19 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_section_cover_image_delete_sectionimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionfile",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="sectionfile",
            name="zip_file",
            field=models.FileField(
                blank=True,
                upload_to="section_file/%Y/%m/%d",
                validators=[django.core.validators.FileExtensionValidator(["zip"])],
            ),
        ),
    ]
