# Generated by Django 5.1.2 on 2024-12-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessontakenbystudent",
            name="coach",
        ),
    ]
