# Generated by Django 5.1.5 on 2025-02-07 08:23

import django.core.validators
import django.db.models.deletion
import utils.file_name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="comments",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_image/%Y/%m/%d"
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "video",
                    models.FileField(
                        upload_to=utils.file_name.section_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(["mp4"])
                        ],
                    ),
                ),
                ("video_title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_available", models.BooleanField(db_default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sections",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسمت",
                "verbose_name_plural": "قسمت های دوره",
                "db_table": "course_section",
                "ordering": ("created_at",),
            },
        ),
    ]
