# Generated by Django 5.1.5 on 2025-02-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_sectionfile_expired_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionfile",
            name="is_close",
            field=models.BooleanField(default=False),
        ),
    ]
