# Generated by Django 5.1.5 on 2025-05-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_beststudent_options'),
        ('course', '0007_section_is_last_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'lesson_course')},
        ),
    ]
