# Generated by Django 5.1.5 on 2025-03-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0007_alter_studentbycoach_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("class_name", models.CharField(help_text="نام کلاس")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="coach_less_course",
                        to="accounts.coach",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lesson_course",
                        to="course.course",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="student_lesson_course", to="accounts.student"
                    ),
                ),
            ],
            options={
                "db_table": "lesson_course",
                "ordering": ("-created_at",),
            },
        ),
    ]
