# Generated by Django 5.1.5 on 2025-03-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_lessoncourse_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessoncourse",
            name="progress",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("in_progress", "In Progress"),
                ],
                default="not_started",
                help_text="وضعیت پیشرفت دوره",
                max_length=11,
                null=True,
            ),
        ),
    ]
