# Generated by Django 5.1.5 on 2025-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_certificatetemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
    ]
