# Generated by Django 5.1.5 on 2025-02-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_course_course_price_alter_section_is_available"),
        ("images", "0005_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="section_images",
                to="images.image",
            ),
        ),
        migrations.DeleteModel(
            name="SectionImage",
        ),
    ]
