# Generated by Django 5.1.5 on 2025-03-20 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_remove_sendpractice_practice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendsectionfile",
            name="score",
            field=models.FloatField(
                blank=True,
                help_text="نمره تکلیف ارسالی",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
