# Generated by Django 5.1.5 on 2025-02-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0008_sectionfile_is_close"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendSectionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("zip_file", models.FileField(help_text="فایل ارسالی", upload_to="")),
                (
                    "section_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_files",
                        to="course.sectionfile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="send_section_files",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "db_table": "send_file",
            },
        ),
    ]
