# Generated by Django 5.1.5 on 2025-02-21 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_remove_sectionfile_pdf_file_sectionfile_zip_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionfile",
            name="zip_file",
            field=models.FileField(
                blank=True,
                upload_to="section_file/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(["zip", "rar"])
                ],
            ),
        ),
    ]
