# Generated by Django 5.1.5 on 2025-03-21 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_sendsectionfile_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendsectionfile",
            name="description",
            field=models.TextField(help_text="توضیحی در مورد تمرین ارسالی", null=True),
        ),
        migrations.AlterField(
            model_name="presentabsent",
            name="section",
            field=models.ForeignKey(
                limit_choices_to={"is_publish": True},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="section_present_absent",
                to="course.section",
            ),
        ),
    ]
