# Generated by Django 5.1.5 on 2025-02-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_section_section_image_delete_sectionimage"),
        ("images", "0005_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_image",
                to="images.image",
            ),
        ),
    ]
