# Generated by Django 5.1.5 on 2025-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_studentenrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='student_status',
            field=models.CharField(blank=True, choices=[('active', 'فعال'), ('cancel', 'انصراف'), ('not_paid', 'پرداخت نکرده')], default='active', max_length=8),
        ),
    ]
