# Generated by Django 5.1.5 on 2025-07-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_comment_options_alter_certificate_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestion',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='calllessoncourse',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='lessoncourse',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='onlinelink',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='presentabsent',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('id',), 'permissions': [('can_access_section', 'can access section')]},
        ),
        migrations.AlterModelOptions(
            name='sectionquestion',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='sendsectionfile',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='signupcourse',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='studentaccesssection',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ('id',)},
        ),
    ]
