# Generated by Django 5.1.5 on 2025-03-21 03:48

import course.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_sendsectionfile_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(("rar", "zip"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sendsectionfile",
            name="section_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="section_files",
                to="course.sectionfile",
            ),
        ),
        migrations.AlterField(
            model_name="sendsectionfile",
            name="zip_file",
            field=models.FileField(
                help_text="فایل ارسالی",
                upload_to=course.utils.student_send_section_file,
            ),
        ),
    ]
