# Generated by Django 5.1.5 on 2025-05-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_studentenrollment_student_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
    ]
