# Generated by Django 5.1.5 on 2025-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_accesscourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscourse",
            name="is_coach",
            field=models.BooleanField(default=False),
        ),
    ]
