# Generated by Django 5.1.5 on 2025-03-22 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_alter_certificate_pdf_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("link", models.URLField()),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="online_link",
                        to="course.lessoncourse",
                    ),
                ),
            ],
            options={
                "db_table": "online_link",
            },
        ),
    ]
