# Generated by Django 5.1.5 on 2025-05-23 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_beststudent_options'),
        ('course', '0011_alter_studentenrollment_options_and_more'),
        ('images', '0002_alter_image_options_remove_image_focal_point_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='section_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_question', to='course.sectionquestion'),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_poll_answer', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='calllessoncourse',
            name='lesson_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='call', to='course.lessoncourse'),
        ),
        migrations.AlterField(
            model_name='calllessoncourse',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_call', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_certificate', to='images.image'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_certificates', to='course.section'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_certificates', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_comments', to='course.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_category', to='course.category'),
        ),
        migrations.AlterField(
            model_name='coursetypemodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_type_model', to='course.course'),
        ),
        migrations.AlterField(
            model_name='lessoncourse',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coach_less_course', to='accounts.coach'),
        ),
        migrations.AlterField(
            model_name='lessoncourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='onlinelink',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='online_link', to='course.lessoncourse'),
        ),
        migrations.AlterField(
            model_name='presentabsent',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_present_absent', to='course.section'),
        ),
        migrations.AlterField(
            model_name='presentabsent',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_present_absent', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='course.course'),
        ),
        migrations.AlterField(
            model_name='sectionfile',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_files', to='course.section'),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_question', to='course.section'),
        ),
        migrations.AlterField(
            model_name='sectionvideo',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_videos', to='course.section'),
        ),
        migrations.AlterField(
            model_name='sendsectionfile',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_section_files', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='signupcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_signup', to='course.course'),
        ),
        migrations.AlterField(
            model_name='studentaccesssection',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_section', to='course.section'),
        ),
        migrations.AlterField(
            model_name='studentaccesssection',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_access_section', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='lesson_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_course_enrollment', to='course.lessoncourse'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_enrollment', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='studentsectionscore',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_score', to='course.section'),
        ),
        migrations.AlterField(
            model_name='studentsectionscore',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_section_score', to='accounts.student'),
        ),
    ]
