# Generated by Django 5.1.5 on 2025-03-01 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_accesscourse_is_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendsectionfile",
            name="section_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="section_files",
                to="course.sectionfile",
                validators=[
                    django.core.validators.FileExtensionValidator(["rar", "zip"])
                ],
            ),
        ),
    ]
