# Generated by Django 5.1.5 on 2025-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_onlinelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionfile",
            name="file_type",
            field=models.CharField(
                choices=[("main", "تمرین اصلی"), ("more", "تمرین اضافی")],
                max_length=9,
                null=True,
            ),
        ),
    ]
