# Generated by Django 5.1.5 on 2025-03-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_coach_is_active_student_is_active"),
        ("course", "0011_alter_certificate_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_certificates",
                to="accounts.student",
            ),
        ),
    ]
