# Generated by Django 5.1.5 on 2025-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_sectionfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("main", "تمرین اصلی"),
                    ("more", "تمرین اضافی"),
                    ("gold", "طلایی"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
