# Generated by Django 5.1.5 on 2025-03-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_alter_certificate_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_certificates",
                to="course.course",
            ),
        ),
    ]
