# Generated by Django 5.1.5 on 2025-03-22 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_alter_sectionfile_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionfile",
            name="answer",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="answer/section_file/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(["zip", "rar"])
                ],
            ),
        ),
    ]
