# Generated by Django 5.1.5 on 2025-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_sectionfile_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentaccesssection",
            options={"ordering": ("created_at",)},
        ),
        migrations.RemoveField(
            model_name="presentabsent",
            name="is_present",
        ),
        migrations.AddField(
            model_name="presentabsent",
            name="student_status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر"),
                    ("absent", "غایب"),
                    ("late_attendance", "حضور با تاخیر"),
                    ("inactivity", "عدم فعالیت"),
                ],
                default="present",
            ),
        ),
    ]
