# Generated by Django 5.1.5 on 2025-03-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_coach_is_active_student_is_active"),
        ("course", "0014_alter_certificate_course"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentAccessCourse",
            new_name="AccessCourse",
        ),
        migrations.DeleteModel(
            name="CoachAccessCourse",
        ),
    ]
