# Generated by Django 5.1.5 on 2025-03-25 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0015_alter_studentaccesssection_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("title", models.CharField(max_length=255)),
                ("is_publish", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "coach_question",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="onlinelink",
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="PointToCoach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                (
                    "rate",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                            ("6", "Six"),
                            ("7", "Seven"),
                            ("8", "Eight"),
                            ("9", "Nine"),
                            ("10", "Ten"),
                        ]
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="coach_point",
                        to="accounts.coach",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_point_to_coach",
                        to="accounts.student",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        limit_choices_to={"is_publish": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="points_to_coach",
                        to="course.question",
                    ),
                ),
            ],
            options={
                "db_table": "point_to_coach",
                "ordering": ("-created_at",),
            },
        ),
    ]
