# Generated by Django 5.1.5 on 2025-03-10 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0015_rename_studentaccesscourse_accesscourse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesscourse",
            name="student",
        ),
        migrations.AddField(
            model_name="accesscourse",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_access_course",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
