# Generated by Django 5.1.5 on 2025-03-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_coach_is_active_student_is_active"),
        ("course", "0016_remove_accesscourse_student_accesscourse_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscourse",
            name="coach",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="coach_access_course",
                to="accounts.coach",
            ),
        ),
    ]
