# Generated by Django 5.1.5 on 2025-03-25 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_question_alter_onlinelink_options_pointtocoach"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointtocoach",
            name="section",
            field=models.ForeignKey(
                limit_choices_to={"is_publish": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="section_point_to_coach",
                to="course.section",
            ),
        ),
        migrations.AlterField(
            model_name="pointtocoach",
            name="rate",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ]
            ),
        ),
    ]
