# Generated by Django 5.1.5 on 2025-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0017_accesscourse_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="project_counter",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
