# Generated by Django 5.1.5 on 2025-03-25 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0017_pointtocoach_section_alter_pointtocoach_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointtocoach",
            name="section",
        ),
        migrations.AddField(
            model_name="question",
            name="section",
            field=models.ForeignKey(
                limit_choices_to={"is_publish": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="section_point_to_coach",
                to="course.section",
            ),
        ),
    ]
