# Generated by Django 5.1.5 on 2025-03-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_course_project_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_duration",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_price",
        ),
    ]
