# Generated by Django 5.1.5 on 2025-03-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0018_remove_pointtocoach_section_question_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="section",
        ),
        migrations.AlterModelTable(
            name="question",
            table="poll_question",
        ),
        migrations.CreateModel(
            name="SectionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "question",
                    models.ForeignKey(
                        limit_choices_to={"is_publish": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="points_to_coach",
                        to="course.question",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        limit_choices_to={"is_publish": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_question",
                        to="course.section",
                    ),
                ),
            ],
            options={
                "db_table": "section_question",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AnswerQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                (
                    "rate",
                    models.CharField(
                        verbose_name=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ]
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_poll_answer",
                        to="accounts.student",
                    ),
                ),
                (
                    "section_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="section_question",
                        to="course.sectionquestion",
                    ),
                ),
            ],
            options={
                "db_table": "poll_answer",
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="PointToCoach",
        ),
    ]
