# Generated by Django 5.1.5 on 2025-03-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0019_remove_question_section_alter_question_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerquestion",
            name="rate",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ]
            ),
        ),
    ]
