# Generated by Django 5.1.5 on 2025-03-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0019_remove_course_course_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("-created_at",),
                "permissions": [("can_view_course", "api Can View Course")],
                "verbose_name": "درس",
                "verbose_name_plural": "درس ها",
            },
        ),
    ]
