# Generated by Django 5.1.5 on 2025-03-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("course", "0020_alter_answerquestion_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionquestion",
            name="question",
        ),
        migrations.AddField(
            model_name="sectionquestion",
            name="question_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="answerquestion",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_poll_answer",
                to="accounts.student",
            ),
        ),
    ]
