# Generated by Django 5.1.5 on 2025-03-11 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_coach_is_active_student_is_active"),
        ("course", "0020_alter_course_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccessCourse",
            new_name="Purchases",
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "درس",
                "verbose_name_plural": "درس ها",
            },
        ),
        migrations.RemoveField(
            model_name="lessoncourse",
            name="progress",
        ),
        migrations.AddField(
            model_name="course",
            name="progress",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("finished", "Finished"),
                    ("in_progress", "In Progress"),
                ],
                default="not_started",
                help_text="وضعیت پیشرفت کلاس",
                max_length=11,
                null=True,
            ),
        ),
    ]
