# Generated by Django 5.1.5 on 2025-03-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0021_rename_accesscourse_purchases_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="progress",
        ),
        migrations.AddField(
            model_name="lessoncourse",
            name="progress",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("finished", "Finished"),
                    ("in_progress", "In Progress"),
                ],
                default="not_started",
                help_text="وضعیت پیشرفت کلاس",
                max_length=11,
                null=True,
            ),
        ),
    ]
