# Generated by Django 5.1.5 on 2025-03-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0021_remove_sectionquestion_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendsectionfile",
            name="send_file_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sending", "ارسال شده"),
                    ("accept_to_wait", "در انتظا تایید"),
                    ("accepted", "تایید شده"),
                ],
                default="accept_to_wait",
                help_text="وضعیت فایل ارسالی",
                max_length=14,
                null=True,
            ),
        ),
    ]
