# Generated by Django 5.1.5 on 2025-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_remove_course_progress_lessoncourse_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="project_counter",
        ),
        migrations.AddField(
            model_name="section",
            name="project_counter",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
