# Generated by Django 5.1.5 on 2025-03-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_sendsectionfile_send_file_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sendsectionfile",
            old_name="description",
            new_name="comment_student",
        ),
    ]
