# Generated by Django 5.1.5 on 2025-03-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0023_remove_course_project_counter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="project_counter",
        ),
        migrations.AddField(
            model_name="course",
            name="project_counter",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
