# Generated by Django 5.1.5 on 2025-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0023_rename_description_sendsectionfile_comment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendsectionfile",
            name="comment_teacher",
            field=models.CharField(
                blank=True,
                help_text="توضیح مربی در مورد فایل ارسال شده دانشجو",
                max_length=255,
                null=True,
            ),
        ),
    ]
