# Generated by Django 5.1.5 on 2025-03-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0025_alter_sectionfile_file_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsectionscore",
            name="is_completed",
        ),
    ]
