# Generated by Django 5.1.5 on 2025-03-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0026_remove_studentsectionscore_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendsectionfile",
            name="section_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_files",
                to="course.sectionfile",
            ),
        ),
    ]
