# Generated by Django 5.1.5 on 2025-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0027_alter_sendsectionfile_section_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendsectionfile",
            name="send_file_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rejected", "رد شده"),
                    ("accept_to_wait", "در انتظا تایید"),
                    ("accepted", "تایید شده"),
                ],
                default="accept_to_wait",
                help_text="وضعیت فایل ارسالی",
                max_length=14,
                null=True,
            ),
        ),
    ]
