# Generated by Django 5.1.5 on 2025-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0028_alter_sendsectionfile_send_file_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerquestion",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterField(
            model_name="presentabsent",
            name="student_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("present", "حاضر"),
                    ("absent", "غایب"),
                    ("late_attendance", "حضور با تاخیر"),
                    ("inactivity", "عدم فعالیت"),
                ],
                default="present",
                null=True,
            ),
        ),
    ]
