# Generated by Django 5.1.5 on 2025-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0029_alter_answerquestion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentabsent",
            name="student_status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر"),
                    ("absent", "غایب"),
                    ("late_attendance", "حضور با تاخیر"),
                    ("inactivity", "عدم فعالیت"),
                    ("nothing", "خالی"),
                ],
                default="nothing",
            ),
        ),
    ]
