# Generated by Django 5.1.5 on 2025-03-30 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0032_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="category_comments",
                to="course.category",
            ),
        ),
    ]
