# Generated by Django 5.1.5 on 2025-03-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_privatenotification"),
        ("course", "0033_alter_comment_category"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="presentabsent",
            constraint=models.UniqueConstraint(
                fields=("section", "student"), name="unique_section_student"
            ),
        ),
    ]
