# Generated by Django 5.1.5 on 2025-03-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0034_presentabsent_unique_section_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presentabsent",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="presentabsent",
            name="is_deleted",
        ),
    ]
