# Generated by Django 5.1.5 on 2025-03-31 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0035_remove_presentabsent_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="category",
        ),
        migrations.AddField(
            model_name="comment",
            name="class_room",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="class_room_comments",
                to="course.lessoncourse",
            ),
            preserve_default=False,
        ),
    ]
