# Generated by Django 5.1.5 on 2025-03-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0036_remove_comment_category_comment_class_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="class_room",
        ),
        migrations.AddField(
            model_name="comment",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="category_comments",
                to="course.category",
            ),
            preserve_default=False,
        ),
    ]
