# Generated by Django 5.1.5 on 2025-04-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0037_remove_comment_class_room_comment_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLessonCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("call", models.CharField(help_text="تماس", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("successful", "موفق"),
                            ("un_successful", "ناموفق"),
                            ("nothing", "چیزی ثبت نشده هست"),
                        ],
                        db_index=True,
                        help_text="وضعیت تماس",
                        max_length=13,
                    ),
                ),
                (
                    "call_answering",
                    models.CharField(help_text="پاسخگوی تماس", max_length=20),
                ),
                ("project", models.CharField(help_text="بابت پروژه", max_length=30)),
                ("phase", models.CharField(help_text="فاز", max_length=30)),
                ("call_date", models.DateField(help_text="تاریخ مکالمه")),
                ("result_call", models.TextField(help_text="نتیجه مکالمه")),
                (
                    "cancellation_alert",
                    models.BooleanField(default=False, help_text="هشدار انصراف"),
                ),
                (
                    "lesson_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="call",
                        to="course.lessoncourse",
                    ),
                ),
            ],
            options={
                "db_table": "call_lesson_course",
            },
        ),
    ]
