# Generated by Django 5.1.5 on 2025-04-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ticketroom_subject_room'),
        ('course', '0038_calllessoncourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllessoncourse',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_call', to='accounts.student'),
        ),
    ]
