# Generated by Django 5.1.5 on 2025-04-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_calllessoncourse_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllessoncourse',
            options={'ordering': ('-created_at',)},
        ),
    ]
