# Generated by Django 5.1.5 on 2025-04-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_alter_calllessoncourse_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllessoncourse',
            name='phase',
        ),
    ]
