# Generated by Django 5.1.5 on 2025-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_remove_calllessoncourse_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, help_text='قیمت دوره', null=True),
        ),
    ]
