# Generated by Django 5.1.5 on 2025-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_course_is_free_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
