# Generated by Django 5.1.5 on 2025-04-15 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_alter_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('basic', 'مقدماتی'), ('indeterminate', 'متوسط'), ('advanced', 'پیشرفته')], default='basic', max_length=13),
        ),
        migrations.AddField(
            model_name='course',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
