# Generated by Django 5.1.5 on 2025-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_course_course_type_course_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_age',
            field=models.CharField(blank=True, help_text='بازه سنی دوره', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='time_course',
            field=models.CharField(blank=True, help_text='مدت زمان دوره', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
