# Generated by Django 5.1.5 on 2025-04-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_course_course_age_course_time_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='course',
        ),
        migrations.AddField(
            model_name='certificate',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_publish': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_certificates', to='course.section'),
        ),
    ]
