# Generated by Django 5.1.5 on 2025-04-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_remove_certificate_course_certificate_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_file',
        ),
    ]
