# Generated by Django 5.1.5 on 2025-04-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0047_remove_certificate_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('student_name', models.CharField(help_text='نام و نام خوادگی داشن اموز', max_length=120)),
                ('phone_number', models.CharField(help_text='شماره تلف ', max_length=15)),
                ('i_have_computer', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_signup', to='course.course')),
            ],
            options={
                'db_table': 'course_signup',
            },
        ),
    ]
