# Generated by Django 5.1.5 on 2025-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0048_signupcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcourse',
            name='phone_number',
            field=models.CharField(help_text='شماره تلفن ', max_length=15),
        ),
    ]
