# Generated by Django 5.1.5 on 2025-05-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0049_alter_signupcourse_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/%Y/%m/%d'),
        ),
    ]
