# Generated by Django 5.1.5 on 2025-05-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0050_category_description_category_image'),
        ('subscription_app', '0009_alter_plan_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='plans',
            field=models.ManyToManyField(blank=True, to='subscription_app.plan'),
        ),
    ]
