# Generated by Django 5.1.5 on 2025-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0051_course_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('private', 'خصوصی'), ('economy', 'اکونومی')], max_length=7),
        ),
    ]
