# Generated by Django 5.1.5 on 2025-05-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0052_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
