# Generated by Django 5.1.5 on 2025-05-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0053_course_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='plans',
        ),
        migrations.CreateModel(
            name='CourseTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('course_type', models.CharField(choices=[('private', 'خصوصی'), ('economy', 'اکونومی')], default='private', max_length=8)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_type_model', to='course.course')),
            ],
            options={
                'db_table': 'course_type',
            },
        ),
    ]
