# Generated by Django 5.1.5 on 2025-05-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0054_remove_course_plans_coursetypemodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetypemodel',
            unique_together={('course_type', 'course')},
        ),
    ]
