# Generated by Django 5.1.5 on 2025-05-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0055_alter_coursetypemodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupcourse',
            name='i_have_computer',
        ),
    ]
