# Generated by Django 5.1.5 on 2025-05-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0056_remove_signupcourse_i_have_computer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
