# Generated by Django 5.1.5 on 2025-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0057_remove_course_course_type_remove_course_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetypemodel',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetypemodel',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('month', 'ماه'), ('year', 'سال'), ('day', 'روز')], max_length=5),
        ),
    ]
