# Generated by Django 5.1.5 on 2025-05-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0058_coursetypemodel_amount_coursetypemodel_plan_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetypemodel',
            unique_together=set(),
        ),
    ]
