# Generated by Django 5.1.5 on 2025-05-10 00:40

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0059_alter_coursetypemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to='certificate/%Y/%m/%d', validators=[course.validators.max_upload_image_validator]),
        ),
        migrations.AlterField(
            model_name='coursetypemodel',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
