# Generated by Django 5.1.5 on 2025-03-03 00:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="شماره همراه"
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        help_text="کد کوپن که در صورت وارد نکردن به صورت رندوم تولید خواهد شدبه این توجه داشته باشید که این ها حتما باید یکتا باشد",
                        max_length=15,
                        unique=True,
                        verbose_name="کد کوپن",
                    ),
                ),
                (
                    "max_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="حداکثر استفاده از کوپن",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "number_of_uses",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="تعداد استقاده شده از کوپن",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expired_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="میتوانید برای کد تخفیف خود یک تاریخ انقضایی داشته باشید",
                        null=True,
                        verbose_name=" تاریخ انقضا",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("amount", models.FloatField()),
                ("is_percent", models.BooleanField(db_default=False)),
                ("is_value", models.BooleanField(db_default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="discounts",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
