# Generated by Django 5.1.2 on 2024-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="expired_date",
            field=models.DateField(blank=True, null=True, verbose_name=" تاریخ انقضا"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
