# Generated by Django 5.1.2 on 2024-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_coupon_expired_date_alter_coupon_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expired_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name=" تاریخ انقضا"
            ),
        ),
    ]
