# Generated by Django 5.1.5 on 2025-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_alter_coupon_deleted_at_alter_coupon_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
