# Generated by Django 5.1.2 on 2024-12-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_alter_coupon_expired_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="mobile_phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره همراه"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="number_of_uses",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="تعداد استقاده شده از کوپن"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                help_text="کد کوپن که در صورت وارد نکردن به صورت رندوم تولید خواهد شدبه این توجه داشته باشید که این ها حتما باید یکتا باشد",
                max_length=15,
                unique=True,
                verbose_name="کد کوپن",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="حداکثر استفاده از کوپن"
            ),
        ),
    ]
