# Generated by Django 5.1.2 on 2024-12-13 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0004_coupon_mobile_phone_coupon_number_of_uses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="حداکثر استفاده از کوپن",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="number_of_uses",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="تعداد استقاده شده از کوپن",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
