# Generated by Django 5.1.5 on 2025-05-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
