# Generated by Django 5.1.5 on 2025-04-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0049_alter_signupcourse_phone_number'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('fist_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_singup', to='course.course')),
            ],
            options={
                'db_table': 'signup_course',
            },
        ),
    ]
