# Generated by Django 5.1.5 on 2025-05-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_answerquestion_section_question_and_more'),
        ('order_app', '0002_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesignup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_signup_one', to='course.course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='course.course'),
        ),
    ]
