# Generated by Django 5.1.5 on 2025-05-08 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0057_remove_course_course_type_remove_course_is_free_and_more'),
        ('order_app', '0002_coursesignup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('price', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
