# Generated by Django 5.1.5 on 2025-05-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0059_alter_coursetypemodel_unique_together'),
        ('order_app', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesignup',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='coursesignup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_signup_one', to='course.course'),
        ),
    ]
