# Generated by Django 5.1.5 on 2025-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_rename_fist_name_coursesignup_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesignup',
            name='have_account',
            field=models.BooleanField(default=False),
        ),
    ]
