# Generated by Django 6.1 on 2026-09-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncourse',
            options={'ordering': ('id',)},
        ),
    ]
