# Generated by Django 5.1.5 on 2025-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_answerquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionvideo',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
