# Generated by Django 5.1.5 on 2025-07-10 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_sectionvideo_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='section_video/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
