# Generated by Django 5.1.5 on 2025-09-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
