# Generated by Django 5.1.5 on 2025-09-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_category_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('id', 'order_number'), name='unique_order_per_course_id'),
        ),
    ]
