# Generated by Django 5.2.7 on 2025-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_course_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncourse',
            name='for_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
