# Generated by Django 5.1.2 on 2024-11-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image_base64",
        ),
    ]
