# Generated by Django 5.1.5 on 2025-05-11 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_invasion', to='accounts.student')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_invasion', to='accounts.student')),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
    ]
