# Generated by Django 5.1.5 on 2025-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatenotification',
            name='char_link',
            field=models.CharField(blank=True, help_text='link for redirect', max_length=50, null=True),
        ),
    ]
