# Generated by Django 5.1.5 on 2025-02-12 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="is_close",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="reply_to",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="subject_ticket",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="user",
        ),
        migrations.AddField(
            model_name="ticket",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TicketRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                (
                    "title_room",
                    models.CharField(help_text="عنوان چت روم تیکت", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_close", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ticker_room",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ticker_room",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="room",
                to="accounts.ticketroom",
            ),
        ),
    ]
