# Generated by Django 5.1.5 on 2025-02-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="coach_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
