# Generated by Django 5.1.5 on 2025-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="mobile phone"
            ),
        ),
    ]
