# Generated by Django 5.1.5 on 2025-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_number",
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
