# Generated by Django 5.1.2 on 2024-12-13 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="admin",
        ),
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                default=0,
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ticket",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
