# Generated by Django 5.1.5 on 2025-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="coach",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="coach",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="coach",
            name="years_of_experience",
        ),
        migrations.RemoveField(
            model_name="student",
            name="bio",
        ),
        migrations.AddField(
            model_name="coach",
            name="coach_number",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
