# Generated by Django 5.1.2 on 2024-11-03 11:01

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_city",
                to="accounts.city",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "پسر"), ("Female", "دختر")],
                max_length=6,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one", "اول"),
                    ("two", "دوم"),
                    ("three", "سوم"),
                    ("four", "چهارم"),
                    ("five", "پنجم"),
                    ("six", "ششم"),
                    ("seven", "هفتم"),
                    ("eight", "هشتم"),
                    ("nine", "نهم"),
                    ("ten", "دهم"),
                    ("eleven", "یازدهم"),
                    ("twelfth", "دوازدهم"),
                    ("graduate", "فارغ التحصیل"),
                ],
                max_length=8,
                null=True,
                verbose_name="grade",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nation_code",
            field=models.CharField(
                max_length=10,
                validators=[accounts.validators.NationCodeRegexValidator()],
                verbose_name="کد ملی",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_school",
                to="accounts.school",
                verbose_name="مدرسه",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="state",
                to="accounts.state",
                verbose_name="استان",
            ),
        ),
    ]
