# Generated by Django 5.1.5 on 2025-04-04 15:29

import api.v1.user.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_privatenotification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ("created_at",),
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_image",
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api.v1.user.utils.ticket_file_upload_url,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="room",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="room",
                to="accounts.ticketroom",
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api.v1.user.utils.ticket_file_upload_url,
            ),
        ),
    ]
