# Generated by Django 5.1.2 on 2024-11-08 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_image_base64"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("ticker_body", models.TextField(verbose_name="متن تیکت")),
                (
                    "subject_ticket",
                    models.CharField(max_length=255, verbose_name="عنوان تیکت"),
                ),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "coach",
                    models.ForeignKey(
                        limit_choices_to={
                            "is_active": True,
                            "is_coach": True,
                            "is_deleted": False,
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coach_ticker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مربی",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        limit_choices_to={
                            "user__is_active": True,
                            "user__is_deleted": False,
                            "user__is_staff": True,
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_ticket",
                        to="departments.department",
                        verbose_name="کاربر ادمین",
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
                "db_table": "ticket",
            },
        ),
    ]
