# Generated by Django 5.1.5 on 2025-02-12 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_ticket_is_close_remove_ticket_reply_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="room",
                to="accounts.ticketroom",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="sender",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
