# Generated by Django 5.1.5 on 2025-05-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_referral_code_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beststudent',
            options={'ordering': ('-created_at',)},
        ),
    ]
