# Generated by Django 5.1.5 on 2025-03-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_mobile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
