# Generated by Django 5.1.2 on 2024-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_user_city_alter_user_gender_alter_user_grade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ نولد"),
        ),
    ]
