# Generated by Django 5.1.2 on 2024-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city",
            field=models.CharField(db_index=True, max_length=30, verbose_name="شهر"),
        ),
    ]
