# Generated by Django 5.1.2 on 2024-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="نام مدرسه"
            ),
        ),
        migrations.DeleteModel(
            name="School",
        ),
    ]
