# Generated by Django 5.1.2 on 2024-11-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_city_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city",
            field=models.CharField(db_index=True, max_length=40, verbose_name="شهر"),
        ),
    ]
