# Generated by Django 5.1.5 on 2025-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_coach_deleted_at_alter_coach_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
