# Generated by Django 5.1.5 on 2025-02-12 16:54

import api.v1.user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_ticket_room_alter_ticket_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.v1.user.utils.ticket_image_upload_url,
                validators=[api.v1.user.utils.ticket_validate_image],
            ),
        ),
    ]
