# Generated by Django 5.1.2 on 2024-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_birth_date"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city",
            field=models.CharField(max_length=30, verbose_name="شهر"),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("state_name", "city")},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nation_code__isnull", True)),
                fields=("nation_code",),
                name="unique_nation_code_if_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("second_mobile_phone__isnull", True)),
                fields=("second_mobile_phone",),
                name="unique_second_mobile_phone_if_not_null",
            ),
        ),
    ]
