# Generated by Django 5.1.5 on 2025-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_privatenotification_char_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, upload_to='ticket/%Y/%m/%d'),
        ),
    ]
