# Generated by Django 5.1.5 on 2025-04-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_ticket_options_remove_ticket_ticket_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "تیکت", "verbose_name_plural": "تیکت ها"},
        ),
        migrations.DeleteModel(
            name="TicketReply",
        ),
    ]
