# Generated by Django 5.1.5 on 2025-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_beststudent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenotification',
            name='char_link',
            field=models.CharField(blank=True, help_text='link for redirect', max_length=30, null=True),
        ),
    ]
