# Generated by Django 5.1.2 on 2024-11-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_school_delete_school"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_emai_if_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_nation_code_if_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_second_mobile_phone_if_not_null",
        ),
    ]
