# Generated by Django 5.1.5 on 2025-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_privatenotification_char_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenotification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
