# Generated by Django 5.1.5 on 2025-06-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ticket_ticket_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ('-id',)},
        ),
    ]
