# Generated by Django 5.1.5 on 2025-02-12 22:44

import api.v1.user.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_ticket_ticket_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["created_at"],
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
        migrations.CreateModel(
            name="TicketReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("message", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.v1.user.utils.ticket_image_upload_url,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sender",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reply_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reply",
                        to="accounts.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_reply",
                "ordering": ["created_at"],
            },
        ),
    ]
