# Generated by Django 5.1.2 on 2024-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_city_city_alter_city_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_image/%Y/%m/%d",
                verbose_name="عکس کاربر",
            ),
        ),
    ]
