# Generated by Django 5.1.5 on 2025-02-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_coach_is_deleted_alter_student_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reply",
                to="accounts.ticket",
            ),
        ),
    ]
