# Generated by Django 5.1.5 on 2025-02-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_ticket_options_ticket_reply_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="ticker_body",
            new_name="ticket_body",
        ),
    ]
