# Generated by Django 5.1.2 on 2024-11-14 21:44

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_unique_emai_if_not_null_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={
                "ordering": ("created_at",),
                "verbose_name": "کد",
                "verbose_name_plural": "کد ها",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="nation_code",
            field=models.CharField(
                max_length=10,
                null=True,
                unique=True,
                validators=[accounts.validators.NationCodeRegexValidator()],
                verbose_name="کد ملی",
            ),
        ),
    ]
