# Generated by Django 5.1.5 on 2025-02-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_ticket_options_ticketreply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userip",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userlogins",
            name="user",
        ),
        migrations.CreateModel(
            name="BestStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="best_student",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "db_table": "best_student",
            },
        ),
        migrations.CreateModel(
            name="BestStudentAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("attribute", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "best_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="best_student",
                        to="accounts.beststudent",
                    ),
                ),
            ],
            options={
                "db_table": "best_student_attribute",
            },
        ),
        migrations.DeleteModel(
            name="UserDevice",
        ),
        migrations.DeleteModel(
            name="UserIp",
        ),
        migrations.DeleteModel(
            name="UserLogins",
        ),
    ]
