# Generated by Django 5.1.5 on 2025-06-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_invitation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='from_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_invasion', to='accounts.student', verbose_name='از دانش اموز'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_invasion', to='accounts.student', verbose_name='به داشن اموز'),
        ),
    ]
