# Generated by Django 5.1.5 on 2025-04-04 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_ticket_depth_ticket_numchild_ticket_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_active": True, "is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ticket_reply",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
