# Generated by Django 5.1.2 on 2024-11-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_city_state_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="state_name",
            new_name="state",
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("state", "city")},
        ),
    ]
