# Generated by Django 5.1.5 on 2025-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_ticker_body_ticket_ticket_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_close",
            field=models.BooleanField(default=False),
        ),
    ]
