# Generated by Django 5.1.5 on 2025-07-02 10:45

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invitation_from_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('-id',), 'verbose_name': 'کد', 'verbose_name_plural': 'کد ها'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nation_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[accounts.validators.NationCodeRegexValidator()], verbose_name='کد ملی'),
        ),
    ]
