# Generated by Django 5.1.5 on 2025-04-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_ticket_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketroom",
            name="subject_room",
            field=models.CharField(help_text="موضوع تیکت", max_length=50, null=True),
        ),
    ]
