# Generated by Django 5.1.2 on 2024-11-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_state_name_city_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cites",
                related_query_name="xxx",
                to="accounts.state",
                verbose_name="استان",
            ),
        ),
    ]
