# Generated by Django 5.1.5 on 2025-02-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_userip_user_remove_userlogins_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beststudent",
            old_name="user",
            new_name="student",
        ),
    ]
