# Generated by Django 5.1.5 on 2025-07-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otp_options_alter_user_nation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='coupon_code',
            field=models.CharField(blank=True, editable=False, help_text='کد تخفیف دعوت شده کاربر', max_length=255, null=True),
        ),
    ]
