# Generated by Django 5.1.5 on 2025-02-17 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_user_beststudent_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beststudent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="beststudentattribute",
            name="best_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="attributes",
                to="accounts.beststudent",
            ),
        ),
    ]
