# Generated by Django 5.1.2 on 2024-11-17 09:14

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecycleUser",
            fields=[],
            options={
                "verbose_name": "کاربر پاک شده",
                "verbose_name_plural": "کاربران پاک شده",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="city",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
