# Generated by Django 5.1.5 on 2025-07-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_invitation_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='coupon_code',
        ),
    ]
