# Generated by Django 5.1.5 on 2025-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
