# Generated by Django 5.1.5 on 2025-02-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_beststudent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beststudent",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
