# Generated by Django 5.1.2 on 2024-11-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_recycleuser_alter_city_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_student",
        ),
    ]
