# Generated by Django 5.1.5 on 2025-02-22 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_beststudent_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="beststudent",
            name="attributes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="beststudent",
            name="student_image",
            field=models.ImageField(null=True, upload_to="best_student_image/%Y/%m"),
        ),
        # migrations.DeleteModel(
        #     name="BestStudentAttribute",
        # ),
    ]
