# Generated by Django 5.1.5 on 2025-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_privatenotification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenotification',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
