# Generated by Django 5.1.5 on 2025-07-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_invitation_coupon_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
    ]
