# Generated by Django 5.1.5 on 2025-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_privatenotification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatenotification',
            name='body',
            field=models.TextField(),
        ),
    ]
