# Generated by Django 5.1.5 on 2025-02-24 16:14

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_beststudent_attributes_beststudent_student_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "دانش اموز",
                "verbose_name_plural": "دانش اموزان",
            },
        ),
        migrations.AlterField(
            model_name="beststudent",
            name="student",
            field=models.CharField(help_text="نام دانش اموز", max_length=50),
        ),
        migrations.AlterField(
            model_name="beststudent",
            name="student_image",
            field=models.ImageField(
                help_text="حجم عکس اپلودی نباید بیش تر از یک مگابایت باشد",
                null=True,
                upload_to="best_student_image/%Y/%m/%d",
                validators=[accounts.validators.validate_upload_image_user],
            ),
        )
    ]
