# Generated by Django 5.1.5 on 2025-04-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_privatenotification_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatenotification',
            options={'ordering': ('-created_at',)},
        ),
    ]
