# Generated by Django 5.1.5 on 2025-05-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_privatenotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='referral_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
