# Generated by Django 5.2.8 on 2025-12-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beststudent',
            options={'ordering': ('-created_at',), 'verbose_name': 'دانش اموز برتر', 'verbose_name_plural': 'دانش اموزان برتر'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ('-id',), 'verbose_name': 'دعوت', 'verbose_name_plural': 'دعوت ها'},
        ),
        migrations.AlterModelOptions(
            name='privatenotification',
            options={'ordering': ('-created_at',), 'verbose_name': 'نوتیفیکیشن کاربر', 'verbose_name_plural': 'نوتیفیکیشن های کاربر'},
        ),
        migrations.AlterModelOptions(
            name='requestlog',
            options={'verbose_name': 'لاگ درخواست', 'verbose_name_plural': 'لاگ های درخواست'},
        ),
        migrations.AlterModelOptions(
            name='ticketroom',
            options={'ordering': ('-created_at',), 'verbose_name': 'اتاق تیکت', 'verbose_name_plural': 'اتاق های تیکت'},
        ),
    ]
