# Generated by Django 5.2.8 on 2025-12-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_beststudent_options_alter_invitation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
    ]
