# Generated by Django 5.2.8 on 2025-12-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_coach_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecycleUser',
        ),
    ]
