# Generated by Django 5.1.5 on 2025-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('slug_text', models.TextField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('changefreq', models.CharField(max_length=255)),
                ('priority', models.DecimalField(decimal_places=2, default=0.5, help_text='A value between 0.00 and 1.00', max_digits=3)),
            ],
            options={
                'db_table': 'site_map',
            },
        ),
    ]
