# Generated by Django 5.1.5 on 2025-07-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitemapentry_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('user_counter', models.CharField(blank=True, max_length=10)),
                ('task_counter', models.CharField(blank=True, max_length=10)),
                ('class_counter', models.CharField(max_length=10)),
                ('video_counter', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'course_site_information',
            },
        ),
    ]
