# Generated by Django 5.1.5 on 2025-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("expired", "منقضی شده"),
                    ("nothing", "هیچ"),
                ],
                default="nothing",
                max_length=7,
            ),
        ),
    ]
