# Generated by Django 5.1.5 on 2025-05-10 21:46

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='mobile_phone',
            field=models.CharField(db_index=True, max_length=11, null=True, validators=[accounts.validators.MobileRegexValidator()]),
        ),
    ]
