# Generated by Django 5.1.5 on 2025-05-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('subscription_app', '0002_remove_subscription_user_subscription_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='crud_course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.coursetypemodel'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
