# Generated by Django 5.1.5 on 2025-02-08 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_app", "0002_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("plan_title", models.CharField(help_text="عنوان پلن")),
                ("number_of_days", models.PositiveSmallIntegerField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                ("description", models.TextField(help_text="توضیحی در مورد پلن")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "plan",
            },
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("expired", "منقضی شده"),
                    ("nothing", "هیچ"),
                    ("waiting", "انتظار"),
                    ("delete", "حذف شده"),
                ],
                default="nothing",
                max_length=7,
            ),
        ),
    ]
