# Generated by Django 5.1.5 on 2025-04-13 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0002_alter_subscription_options_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='قابل انتشار باشد یا خیر'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, help_text='رایگان هست؟'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='number_of_days',
            field=models.PositiveSmallIntegerField(help_text='تعداد روز پلن'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(help_text='قیمت', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
