# Generated by Django 5.1.5 on 2025-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_app", "0003_alter_accesscourse_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscourse",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
