# Generated by Django 5.1.5 on 2025-04-13 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0003_alter_plan_is_active_alter_plan_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False, help_text='رایگان هست؟'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(blank=True, help_text='قیمت', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
