# Generated by Django 5.1.5 on 2025-04-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0004_alter_plan_is_free_alter_plan_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created_at',), 'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک\u200cها'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
