# Generated by Django 5.1.5 on 2025-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0004_remove_subscription_mobile_phone_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
