# Generated by Django 5.1.5 on 2025-04-14 21:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0005_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
