# Generated by Django 5.1.5 on 2025-05-16 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0005_remove_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('response_payment', models.JSONField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_subscription', to='subscription_app.subscription')),
            ],
            options={
                'db_table': 'payment_subscription',
            },
        ),
    ]
