# Generated by Django 5.1.5 on 2025-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0006_plan_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='number_of_days',
            field=models.CharField(choices=[('1', 'یک ماهه'), ('2', 'دو ماهه'), ('3', 'سه ماهه'), ('4', 'چهار ماهه'), ('5', 'پنج ماهه'), ('6', 'شش ماه'), ('7', 'هفت ماه'), ('8', 'هشت ماه'), ('9', 'نه ماهه'), ('10', 'ده ماهه'), ('11', 'یازده ماهه'), ('12', 'دوازده ماهه')], default='1', max_length=10),
        ),
    ]
