# Generated by Django 5.1.5 on 2025-05-19 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0006_paymentsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsubscription',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='PaymentVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('verify_payment', models.JSONField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_verify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_verify',
                'ordering': ('-created_at',),
            },
        ),
    ]
