# Generated by Django 5.1.5 on 2025-04-15 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0007_alter_plan_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='درصد تخفیف (۰ تا ۱۰۰)', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
