# Generated by Django 5.1.5 on 2025-04-15 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0008_plan_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='درصد تخفیف (۰ تا ۱۰۰)', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
