# Generated by Django 5.1.5 on 2025-05-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_alter_coupon_valid_from_alter_coupon_valid_to'),
        ('subscription_app', '0008_subscription_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='discount',
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coupon_subscription', to='discount_app.coupon'),
        ),
    ]
