# Generated by Django 5.1.5 on 2025-05-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0009_remove_subscription_discount_subscription_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentverify',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentverify',
            name='payment_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_verify', to='subscription_app.paymentsubscription'),
        ),
    ]
