# Generated by Django 5.1.5 on 2025-05-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0010_remove_paymentverify_user_paymentverify_payment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentverify',
            name='payment_link',
        ),
    ]
