# Generated by Django 5.1.5 on 2025-05-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created_at',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='focal_point_height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='focal_point_width',
        ),
        migrations.RemoveField(
            model_name='image',
            name='focal_point_x',
        ),
        migrations.RemoveField(
            model_name='image',
            name='focal_point_y',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_base64',
        ),
    ]
