# Generated by Django 5.1.5 on 2025-02-12 16:54

import images.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                height_field="height",
                help_text="max size is 1 MG",
                upload_to="images/%Y/%m/%d",
                validators=[images.validators.validate_image_size],
                width_field="width",
            ),
        ),
    ]
