# Generated by Django 5.1.5 on 2025-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_address',
            field=models.URLField(blank=True, null=True),
        ),
    ]
