# Generated by Django 5.1.5 on 2025-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
