# Generated by Django 5.1.5 on 2025-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_image_deleted_at_alter_image_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
