# Generated by Django 5.1.2 on 2024-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defineadvertise",
            name="interval_minutes",
            field=models.PositiveSmallIntegerField(
                default=120, verbose_name="بازه های زمانی مشاوره"
            ),
        ),
    ]
