# Generated by Django 5.1.2 on 2024-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationrequest",
            name="is_answer",
            field=models.BooleanField(default=False),
        ),
    ]
