# Generated by Django 5.1.5 on 2025-05-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ('-created_at',)},
        ),
    ]
