# Generated by Django 5.1.2 on 2024-12-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationrequest",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation_request_topic",
                to="advertise.consultationtopic",
            ),
        ),
    ]
