# Generated by Django 5.2.8 on 2025-12-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_slot_slot', to='advertise.consultationslot'),
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_slot', to='advertise.consultationschedule'),
        ),
    ]
