# Generated by Django 5.1.5 on 2025-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0002_alter_consultationrequest_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationrequest",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationschedule",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationschedule",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationslot",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationslot",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationtopic",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationtopic",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
