# Generated by Django 5.1.2 on 2024-11-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0002_defineadvertise_interval_minutes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defineadvertise",
            name="end_time",
        ),
    ]
