# Generated by Django 5.1.5 on 2025-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0003_alter_consultationrequest_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationrequest",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationschedule",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationslot",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consultationtopic",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
