# Generated by Django 5.1.2 on 2024-12-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0003_alter_consultationrequest_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationrequest",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="consultation_slot_slot",
                to="advertise.consultationslot",
            ),
        ),
        migrations.AlterField(
            model_name="consultationslot",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="consultation_slot",
                to="advertise.consultationschedule",
            ),
        ),
    ]
