# Generated by Django 5.1.5 on 2025-02-08 19:11

import ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.CharField(
                default=ulid.ULID,
                editable=False,
                max_length=26,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterModelTable(
            name="cart",
            table="cart",
        ),
    ]
