# Generated by Django 5.1.5 on 2025-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
