# Generated by Django 5.1.5 on 2025-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0003_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
