# Generated by Django 5.1.5 on 2025-02-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_added",
            field=models.BooleanField(default=False),
        ),
    ]
