# Generated by Django 5.1.5 on 2025-02-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0006_cart_is_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="order_cart",
                to="cart_app.cart",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="is_added",
            field=models.BooleanField(
                default=False, help_text="ایا به سبد خرید رفته هست یا خیر"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="final_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
