# Generated by Django 5.1.5 on 2025-02-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0007_order_cart_alter_cart_is_added_and_more"),
        ("subscription_app", "0003_plan_alter_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="order_item_plan",
                to="subscription_app.plan",
            ),
        ),
    ]
