# Generated by Django 5.1.5 on 2025-02-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0008_alter_orderitem_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
