# Generated by Django 5.1.5 on 2025-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_exam_user_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_access',
            field=models.BooleanField(default=True),
        ),
    ]
