# Generated by Django 5.1.5 on 2025-06-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_choice_choice_file_alter_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_file',
        ),
    ]
