# Generated by Django 5.1.5 on 2025-06-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0013_participation_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_corrected',
        ),
        migrations.AlterField(
            model_name='answer',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participation_answer', to='exam_app.participation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_answer', to='exam_app.question'),
        ),
    ]
