# Generated by Django 5.1.5 on 2025-06-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_signupcourse_referral_code'),
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, help_text='میتوان دوه ای را انتخاب کرد یا ازمون به دوره خاصی مربوط نباشد', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam', to='course.course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(help_text='توضیح در مورد ازمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='تاریخ شروع ازمون', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exam_app.exam'),
        ),
    ]
