# Generated by Django 5.1.5 on 2025-03-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="number_of_time",
            field=models.DurationField(help_text="مدت زمان ازمون", null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="start_date",
            field=models.DateTimeField(help_text="تاریخ شروع ازمون", null=True),
        ),
    ]
