# Generated by Django 5.1.5 on 2025-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_exam_options_alter_exam_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='تاریخ شروع ازمون میتوانید از یک زمان خاصی بگید ازمون شروع شود یا میتوان ان را خالی گذاشت', null=True),
        ),
    ]
