# Generated by Django 5.1.5 on 2025-03-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam_app", "0002_exam_number_of_time_exam_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="start_date",
            new_name="start_datetime",
        ),
    ]
