# Generated by Django 5.1.5 on 2025-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_app", "0003_rename_start_date_exam_start_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="number_of_time",
            field=models.PositiveSmallIntegerField(
                help_text="مدت زمان ازمون بر اساس دقیقه", null=True
            ),
        ),
    ]
