# Generated by Django 5.1.5 on 2025-06-07 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_exam_start_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='user_access',
            field=models.ManyToManyField(blank=True, related_name='user_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
