# Generated by Django 5.1.5 on 2025-03-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_app", "0004_alter_exam_number_of_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="number_of_time",
            field=models.PositiveSmallIntegerField(
                help_text="مدت زمان ازمون بر اساس دقیقه"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_datetime",
            field=models.DateTimeField(help_text="تاریخ شروع ازمون"),
        ),
    ]
