# Generated by Django 5.1.5 on 2025-06-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_participation_is_access'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
    ]
