# Generated by Django 5.1.5 on 2025-06-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_alter_participation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.AddField(
            model_name='question',
            name='question_file',
            field=models.FileField(blank=True, help_text='پیوست یک فایل برای سوال', null=True, upload_to='question_exam/file/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
