# Generated by Django 5.1.5 on 2025-03-01 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_app", "0006_exam_description_alter_exam_is_active_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.FloatField(
                blank=True,
                help_text="نمره کاربر",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
