# Generated by Django 5.1.5 on 2025-06-07 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_remove_score_exam_remove_score_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=1, help_text='حداکثر نمره قابل کسب برای این سوال', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'چند گزینه\u200cای'), ('DE', 'تشریحی')], default='MC', help_text='نوع سوال', max_length=2),
        ),
    ]
