# Generated by Django 5.1.5 on 2025-03-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_app", "0007_alter_score_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="student_ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="ادرس ای پی کاربر", null=True
            ),
        ),
    ]
