# Generated by Django 5.1.5 on 2025-06-07 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_question_max_score_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('text', models.CharField(help_text='متن گزینه', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='آیا این گزینه صحیح است؟')),
                ('question', models.ForeignKey(limit_choices_to={'type': 'MC'}, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam_app.question')),
            ],
            options={
                'db_table': 'choice',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('given_score', models.PositiveSmallIntegerField(blank=True, help_text='نمره اختصاص داده شده توسط مصحح', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_corrected', models.BooleanField(default=False, help_text='آیا تصحیح شده است؟')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_app.participation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.question')),
                ('selected_choices', models.ManyToManyField(blank=True, to='exam_app.choice')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
