# Generated by Django 5.1.5 on 2025-06-07 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_choice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_file',
            field=models.FileField(blank=True, help_text='در صورتی که نیاز به ارسال فایل هست میتوانید فایل رو ارسال کیند', null=True, upload_to='choice_exam/file/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(limit_choices_to={'question_type': 'MC'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices', to='exam_app.question'),
        ),
    ]
