# Generated by Django 5.1.5 on 2025-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0012_answer_choice_file_alter_answer_given_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='نمره'),
        ),
    ]
