# Generated by Django 5.1.5 on 2025-07-03 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0014_remove_answer_is_corrected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_file',
            field=models.FileField(blank=True, help_text='پیوست یک فایل برای سوالفورمت های مجازzip - pdf - png - jpeg', null=True, upload_to='question_exam/file/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('zip', 'pdf', 'png', 'jpeg'))]),
        ),
    ]
