# Generated by Django 5.1.5 on 2025-06-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryblog',
            name='description_slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
