# Generated by Django 5.1.5 on 2025-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_postblog_description_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryblog',
            name='description_slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='description_slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
