# Generated by Django 5.1.5 on 2025-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_categoryblog_description_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postblog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='categoryblog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
