# Generated by Django 5.1.5 on 2025-06-05 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_postblog_options_categoryblog_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentblog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_likes', to='blog_app.postblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_post_like',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
