# Generated by Django 5.1.5 on 2025-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_postblog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='post_slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
